packages:
  - "apps/auth"
  - "apps/auth-admin"
  - "apps/auth-ui"
  - "apps/auth-policy"
  - "apps/desktop/*"
  - "apps/web/*"
  - "apps/mobile/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@sentry/cli"
  - "better-sqlite3"
  - "electron"
  - "electron-winstaller"
  - "esbuild"
  - "sharp"
  - "supabase"
  - "unrs-resolver"
