export const MANAGER_POWERSYNC_BUCKET = "manger_data";
export const MANAGER_POWERSYNC_DB_FILENAME = "mfc-manager-powersync.db";

export const MANAGER_WEB_PERSISTENT_LOCAL_TABLES = [
  "users",
  "mfc_staff",
  "products",
  "stock_batches",
  "manager_spendings",
] as const;

export const MANAGER_WEB_TODAY_LOCAL_TABLES = [
  "daily_bills",
  "sale_transactions",
  "chalans",
  "customer_payments",
  "seller_payments",
  "manager_spendings",
] as const;

export const MANAGER_READ_MODEL_TABLES = [
  "mfc_staff",
  "users",
  "products",
  "stock_batches",
  "daily_bills",
  "chalans",
  "sale_transactions",
  "customer_payments",
  "seller_payments",
  "manager_spendings",
  "quotes",
  "quote_items",
  "customer_balance",
  "seller_balance",
  "system_config",
] as const;

export type ManagerReadModelTableName = (typeof MANAGER_READ_MODEL_TABLES)[number];

export const MANAGER_READ_MODEL_SELECT_COLUMNS = {
  users: [
    "id",
    "auth_user_id",
    "name",
    "business_name",
    "phone",
    "user_type",
    "default_role",
    "is_active",
    "address",
    "updated_at",
  ],
  mfc_staff: [
    "id",
    "full_name",
    "role",
    "is_active",
    "is_default_admin",
    "updated_at",
  ],
  products: [
    "id",
    "name",
    "description",
    "is_stock_tracked",
    "updated_at",
    "created_by",
  ],
  stock_batches: [
    "id",
    "product_id",
    "batch_code",
    "supplier_id",
    "mfc_seller_id",
    "initial_weight_kg",
    "current_weight_kg",
    "cost_per_kg",
    "updated_at",
    "created_by",
  ],
  daily_bills: [
    "id",
    "bill_number",
    "customer_id",
    "bill_date",
    "total_amount",
    "amount_paid",
    "status",
    "is_migration_bill",
    "updated_at",
    "created_by",
  ],
  sale_transactions: [
    "id",
    "daily_bill_id",
    "chalan_id",
    "stock_batch_id",
    "product_id",
    "product_description",
    "weight_kg",
    "price_per_kg",
    "amount",
    "sale_type",
    "updated_at",
    "created_by",
  ],
  chalans: [
    "id",
    "chalan_number",
    "seller_id",
    "mfc_seller_id",
    "chalan_date",
    "total_sale_value",
    "commission_rate_percent",
    "commission_amount",
    "net_payable",
    "amount_paid",
    "status",
    "updated_at",
    "created_by",
  ],
  quotes: [
    "id",
    "quote_number",
    "customer_id",
    "assigned_mfc_seller_id",
    "delivery_date",
    "total_amount",
    "advance_paid",
    "status",
    "notes",
    "updated_at",
    "created_by",
  ],
  quote_items: [
    "id",
    "quote_id",
    "product_id",
    "product_description",
    "weight_kg",
    "price_per_kg",
    "line_total",
  ],
  customer_payments: [
    "id",
    "daily_bill_id",
    "payment_date",
    "amount",
    "payment_method",
    "updated_at",
    "created_by",
  ],
  seller_payments: [
    "id",
    "chalan_id",
    "payment_date",
    "amount",
    "payment_method",
    "updated_at",
    "created_by",
  ],
  manager_spendings: [
    "id",
    "spent_date",
    "title",
    "category",
    "amount",
    "note",
    "payment_method",
    "updated_at",
    "created_by",
  ],
  customer_balance: [
    "user_id",
    "total_billed",
    "total_paid",
    "current_due",
    "updated_at",
  ],
  seller_balance: [
    "user_id",
    "total_earned",
    "total_paid_out",
    "current_due",
    "updated_at",
  ],
  system_config: [
    "id",
    "default_admin_id",
    "mfc_stock_buyer_id",
  ],
} as const;
